"""product table

Revision ID: 813a22c2d9e5
Revises: 61108d866faa
Create Date: 2024-10-25 14:52:22.228592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813a22c2d9e5'
down_revision = '61108d866faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('genres', sa.String(length=140), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
